export const lightTheme: Record<string, string> = {
  "--bg-base": "#f8f7ff",
  "--bg-surface": "#ffffff",
  "--bg-elevated": "#f5f3ff",
  "--border-subtle": "#e4e0fa",
  "--border-default": "#c4b5fd",
  "--text-primary": "#1a1523",
  "--text-secondary": "#4a4260",
  "--text-muted": "#8b83a3",
  "--accent-primary": "#6d5ce6",
  "--accent-primary-hover": "#5b4bd4",
  "--accent-primary-subtle": "#ede9fe",
  "--accent-primary-border": "#c4b5fd",
  "--accent-primary-text": "#6d5ce6",
  "--accent-green": "#16a34a",
  "--accent-green-subtle": "#f0fdf4",
  "--accent-green-border": "#86efac",
  "--accent-orange": "#c2410c",
  "--accent-orange-subtle": "#fff7ed",
  "--accent-orange-border": "#fed7aa",
  // Code block tokens — light mode uses a soft purple tint
  "--code-bg": "#f0eefb",
  "--code-comment": "#9e97c0",
  "--code-keyword": "#7c3aed",
  "--code-string": "#16a34a",
  "--code-variable": "#2563eb",
  "--code-value": "#c2410c",
  // Inline code chip tokens
  "--code-chip-bg": "#edeaf8",
  "--code-chip-color": "#5b4bd4",
  "--code-chip-border": "#d4cef5",
};
