export const lightTheme: Record<string, string> = {
  "--bg-base": "#f8f7ff",
  "--bg-surface": "#ffffff",
  "--bg-elevated": "#f5f3ff",
  "--border-subtle": "#e4e0fa",
  "--border-default": "#c4b5fd",
  "--text-primary": "#1a1523",
  "--text-secondary": "#4a4260",
  "--text-muted": "#8b83a3",
  "--accent-primary": "#6d5ce6",
  "--accent-primary-hover": "#5b4bd4",
  "--accent-primary-subtle": "#ede9fe",
  "--accent-primary-border": "#c4b5fd",
  "--accent-primary-text": "#6d5ce6",
  "--accent-green": "#16a34a",
  "--accent-green-subtle": "#f0fdf4",
  "--accent-green-border": "#86efac",
  "--accent-orange": "#c2410c",
  "--accent-orange-subtle": "#fff7ed",
  "--accent-orange-border": "#fed7aa",
  // Code block tokens are identical in both themes — editor is always dark
  "--code-bg": "#1e1e2e",
  "--code-comment": "#6c7086",
  "--code-keyword": "#c084fc",
  "--code-string": "#34d399",
  "--code-variable": "#60a5fa",
  "--code-value": "#fb923c",
};
